### ISSUE TITLE
VOC12

### ISSUE THREAD

**Issue by ayyappa1993** [subhc/SPNet#1]
Hi Subhabrata,

Thanks for this wonderful work. Are you planning to update your repo adding the full support for VOC12 dataset? Some parts have the possibility to configure it(for COCO), some others not(VOC), i.e. get_dataset().

Thanks

**Comment by subhc** [comment]
Thank you for your interest. The code is generalized and supports both the datasets. Please use run_pascal.sh - it's configured to run all the experiments on voc12.

**Comment by zhangxgu** [comment]
@subhc These is no code for loading the voc images, so could you please upload this part of code?
